### ISSUE TITLE
Show process output in buffer

### ISSUE THREAD

**Issue by alinnow** [mallt/cmd-to-echo#1]
I've noticed that the normal `*process*` buffer is empty when using `cmd-to-echo`. Is it possible to keep it there, to refer back to?

I tried to investigate, hoping to fix it myself and I found that in the help for `set-process-filter`, once a non-default filter is set for a process, its buffer is not used for output. I wonder if there's some way around this, but couldn't think of anything so far.

**Comment by mallt** [comment]
Hi @alanpearce, all output of the echo area is added to the _Messages_ buffer as well, so you should be able to the find the previous process output there.

Apart from that, we could indeed add an option (defcustom) to also add the output to the _process_ buffers as well. It would be just a matter of adding an `insert` to the cmd-to-echo--proc-filter. I wouldn't set it to true by default, since all output will be duplicated then in the _Messages_ buffer and _process_ buffers.

Or do you think only having all output in the _Messages_ buffer is sufficient?

**Comment by mallt** [comment]
Hi @alanpearce, would you still be interested in seeing the output in the process buffers as well, or are you ok to have it in the `*Messages*` buffer?

**Comment by alinnow** [comment]
It's an odd one. Most of the time, `*Messages*` is fine. The problem is if I leave a long-running command whose previous output I need to check, or have multiple running, then `*Messages*` is harder to use. But I don't do that often, so I'm mostly happy with it in `*Messages*`. I think it would be a good idea to see the output in process buffers, but it's not hurting me.

**Comment by mallt** [comment]
Ok thanks for the feedback! I will add a defcustom to control showing the output in the process buffers.

**Comment by mallt** [comment]
@alanpearce, I've added an option to add the output to the process buffers:
```
(setq cmd-to-echo-add-output-to-process-buffers t)
```
The change should be available in melpa in a couple of hours.
